feat/shimmer-quiz
iota-wiki/iota-wiki pull request #758
Opened 2022-09-27 22:25 UTC by huhn511

# Description of change

add shimmer quiz with several questions.

2022-09-29 20:26 UTC, jlvandenhout requested changes

2022-09-29 20:26 UTC, jlvandenhout commented on shimmer/learn/shimmer-questions.json
> +        { "answerText": "Soon Network", "isCorrect": false },
```suggestion
        { "answerText": "Soon network", "isCorrect": false },
```

2022-09-29 20:26 UTC, jlvandenhout commented on shimmer/learn/shimmer-questions.json
> +      "questionText": "What's the beginning of a Shimmer Testnet address?",
AFAIK it's iether the Shimmer Beta network or just Testent right? As Shimmer is now live, I'd say we stick to just Testnet.

```suggestion
      "questionText": "What's the beginning of a Testnet address?",
```

2022-09-29 20:26 UTC, jlvandenhout commented on shimmer/learn/shimmer-questions.json
> +      "questionText": "How many bytes can be used for the immutable data output, which is used for example for NFT Metadata?",
```suggestion
      "questionText": "How many bytes can be used for the immutable data output, which is used for example for NFT metadata?",
```

2022-09-29 20:26 UTC, jlvandenhout commented on shimmer/learn/shimmer-questions.json
> +      "questionText": "What does DAO stands for?",
```suggestion
      "questionText": "What does DAO stand for?",
```

2022-09-29 20:26 UTC, jlvandenhout commented on shimmer/learn/shimmer-questions.json
> +        { "answerText": "Decentralised Exchange", "isCorrect": true },
```suggestion
        { "answerText": "Decentralized Exchange", "isCorrect": true },
```

We converged to American spelling.

2022-09-29 20:26 UTC, jlvandenhout commented on shimmer/learn/shimmer-questions.json
> +        { "answerText": "Decentralised Aggregated Organisation", "isCorrect": false },
```suggestion
        { "answerText": "Decentralized Autonomous Organisation", "isCorrect": true },
        { "answerText": "Decentralized Aggregated Organisation", "isCorrect": false },
```

2022-09-29 20:26 UTC, jlvandenhout commented on shimmer/learn/shimmer-questions.json
> +      "questionText": "How do we call Tokens on Layer 1 (L1)?",
```suggestion
      "questionText": "What do we call tokens on Layer 1 (L1)?",
```

2022-09-29 20:26 UTC, jlvandenhout commented on shimmer/learn/shimmer-questions.json
> +        { "answerText": "Necend Tokens", "isCorrect": false }
```suggestion
        { "answerText": "Natural tokens", "isCorrect": false },
        { "answerText": "New tokens", "isCorrect": false },
        { "answerText": "Native tokens", "isCorrect": true },
        { "answerText": "Necend tokens", "isCorrect": false }
```

2022-09-29 20:26 UTC, jlvandenhout commented on shimmer/learn/shimmer-questions.json
> +        { "answerText": "a Blockchain", "isCorrect": false }
```suggestion
        { "answerText": "A blockchain", "isCorrect": false }
```

2022-09-30 11:24 UTC, Dr-Electron approved these changes

2022-09-30 13:47 UTC, merged