Update buying.md
iota-wiki/iota-wiki pull request #777
Opened 2022-10-12 00:02 UTC by Phyloiota

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes issue #`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Documentation Fix
- Documentation Enhancement

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have tested the wiki locally and tested that all external links work

2022-10-12 09:04 UTC, Dr-Electron requested changes

2022-10-12 09:04 UTC, Dr-Electron commented on shimmer/learn/token/buying.md
> +- [Iotabee](https://iotabee.com/swap): Swap IOTA for SMR
```suggestion
- [Soonaverse](https://soonaverse.com/tokens/all): Buy with IOTA Tokens
- [Iotabee](https://iotabee.com/swap): Swap IOTA for SMR
```

2022-10-12 09:29 UTC, jlvandenhout requested changes

2022-10-12 09:29 UTC, jlvandenhout commented on shimmer/learn/token/buying.md
> +You can buy Shimmer tokens currently on the following exchanges / marketplaces:
```suggestion
You can buy Shimmer tokens currently on the following exchanges and marketplaces:
```

2022-10-12 09:30 UTC, jlvandenhout approved these changes

2022-10-17 21:05 UTC, Dr-Electron approved these changes

2022-10-17 21:05 UTC, merged