Update _shimmer-community-grant-committee.md
iota-wiki/iota-wiki pull request #887
Opened 2023-02-28 00:38 UTC by Phyloiota

Added informetions about Phase 2 of the selection process changed links to the updated versions of those tools and documents

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes #issue_number`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Documentation Enhancement

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-03-02 14:17 UTC, Dr-Electron requested changes

2023-03-02 14:17 UTC, Dr-Electron commented on shimmer/learn/governance/_shimmer-community-grant-committee.md
> +[**JD Sutton has built a Notion Database for this selection process**](https://airtable.com/shrvZgn3NVsXLTXev/tblAzVWXeTSvUyZI3)
Notion Database? Is that still true? Does this Airtable import from Notion?

2023-03-02 14:17 UTC, Dr-Electron commented on shimmer/learn/governance/_shimmer-community-grant-committee.md
> +[**Proposed structure example Notion by JD Sutton**](https://www.shimmergov.community/treasury-expenses)
Here again. Why mention Notion?

2023-03-05 12:35 UTC, Phyloiota reviewed
fine

2023-03-05 16:03 UTC, Dr-Electron approved these changes

2023-03-05 16:03 UTC, merged