[New Tutorial] Create a simple Voting dApp on ShimmerEVM
iota-wiki/iota-wiki pull request #909
Opened 2023-03-29 15:50 UTC by anistark

# Description of change

[New Tutorial] Create a simple Voting dApp on ShimmerEVM

## Links to any relevant issues

[DevEx Issue #10](https://github.com/iotaledger/guild-devx/issues/10)

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Documentation Enhancement

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work

2023-03-29 17:01 UTC, lucas-tortora commented on tutorials/pages/shimmerevm-dapp-voting.md
> +Now, for instance, to vote, you can assign the action to a button and simply call:
```suggestion
Now you can assign the `contractSigner.vote` action to a button and call:
```

2023-03-29 17:01 UTC, lucas-tortora commented on tutorials/pages/shimmerevm-dapp-voting.md
> +where `i` is the index of the proposal you want to vote for.
```suggestion

* Where `i` is the index of the proposal you want to vote for.
```

2023-03-29 17:01 UTC, lucas-tortora commented on tutorials/pages/shimmerevm-dapp-voting.md
> +## Result
```suggestion
## Result

```

2023-03-29 17:01 UTC, lucas-tortora commented on tutorials/pages/shimmerevm-dapp-voting.md
> +Feel free to make changes to the design to suit your needs.
```suggestion
```

2023-03-29 18:40 UTC, lucas-tortora approved these changes

2023-03-30 09:29 UTC, Dr-Electron commented
First things first:
Can you run `yarn format` to make the action pass? 😆

2023-03-30 17:55 UTC, anistark commented
> First things first: Can you run `yarn format` to make the action pass? 😆
> 
> Than you still need to add the tutorial config to the docusaurus config

Done.

2023-03-30 21:01 UTC, Dr-Electron commented on tutorials/docusaurus.config.js
> +          'isc',
```suggestion
          'text',
          'shimmer',
          'solidity',
          'iscp',
```

2023-03-30 21:03 UTC, Dr-Electron commented on tutorials/pages/shimmerevm-dapp-voting.md
> +You also need to check if the voter has already voted, so you should also add the following conditional :
```suggestion
You also need to check if the voter has already voted, so you should also add the following conditional:
```

2023-03-30 21:04 UTC, Dr-Electron commented on tutorials/pages/shimmerevm-dapp-voting.md
> +![Voting Demo](../static/voting-dapp.jpg 'Voting dApp UI')
```suggestion
![Voting Demo](/voting-dapp.jpg 'Voting dApp UI')
```

2023-03-30 21:14 UTC, anistark commented on tutorials/pages/shimmerevm-dapp-voting.md
> +```solidity!
It adds line number. Looks better and also useful for reference.

2023-03-30 21:32 UTC, Dr-Electron commented on tutorials/pages/shimmerevm-dapp-voting.md
> +```solidity!
Ohh. Didn't know that 🤔 Got it

2023-03-30 21:36 UTC, anistark commented on tutorials/pages/shimmerevm-dapp-voting.md
> +```solidity!
[Hackmd](https://hackmd.io/@anistark/shimmerevm-dapp) for reference.
Now that you mention, not sure if it'll work in docusaurus. 🥲

2023-03-31 13:08 UTC, Dr-Electron approved these changes

2023-03-31 13:08 UTC, Dr-Electron commented on tutorials/pages/shimmerevm-dapp-voting.md
> +
Who do you want to target with this tutorial? 
If beginners then I guess you should also explain this part? If not ignore this comment :)

2023-03-31 13:09 UTC, Dr-Electron requested changes
Sorry, didn't mean to approve 😅

2023-04-03 13:05 UTC, anistark commented on tutorials/pages/shimmerevm-dapp-voting.md
> +Once you have created the `Voter`, you will need `Proposal` `struct` to nominate who to vote on:
Yes.

2023-04-06 13:53 UTC, Dr-Electron commented
Sir, might I ask you to format again? 😆 ❤️

2023-04-06 14:13 UTC, anistark commented
> Sir, might I ask you to format again? 😆 ❤️

done Sir.

2023-04-06 14:13 UTC, anistark commented on tutorials/pages/shimmerevm-dapp-voting.md
> +- **Client Library**: This tutorial will use [Ethers](https://docs.ethers.org/v5/). But you can use any other library that you feel more comfortable in.
I updated it. Removed code editor.

2023-04-06 14:22 UTC, Dr-Electron commented on tutorials/pages/shimmerevm-dapp-voting.md
> +- **Client Library**: This tutorial will use [Ethers](https://docs.ethers.org/v5/). But you can use any other library that you feel more comfortable in.
Ohh. Missed that somehow 🤔

2023-04-06 14:22 UTC, Dr-Electron approved these changes
Let's merge

2023-04-06 14:41 UTC, merged