Docs - Merge Develop and Protocol Docs
iota-wiki/iota-wiki pull request #924
Opened 2023-04-14 15:24 UTC by lucas-tortora

# Description of change

Edited and reorganized the protocol specifications and merged them with the current develop section.

## Links to any relevant issues

fixes https://github.com/iotaledger/guild-devx/issues/64
fixes https://github.com/iotaledger/guild-devx/issues/65

## Type of change

- Documentation Fix

## Change checklist

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work
- [x] I have commented my code, particularly in hard-to-understand areas

## TODO

- [ ]Check for broken links in the rest of the wiki
- [ ] Check for broken links in the other projects

2023-04-16 16:36 UTC, Dr-Electron requested changes
Love this merge. Not sure how I feel about the How-To section yet 😅 .
What is your plan there? Do we want to explain everything there? How about Identity and so on? Would all how tos be explained in this section?

2023-04-16 16:36 UTC, Dr-Electron commented on shimmer/develop/explanations/what-is-shimmer/introduction.md
> +The Shimmer network uses the new [Stardust protocol](../what-is-stardust/welcome.md) that upgrades
Linking to this page leads to a page without sidebar, because that article is not part of the sidebar

2023-04-16 16:36 UTC, Dr-Electron commented on shimmer/develop/explanations/what-is-shimmer/networks.md
> +The [Public test network](../../endpoints/testnet.md) is the testing
Good one 😆

2023-04-16 16:36 UTC, Dr-Electron commented on shimmer/develop/explanations/what-is-stardust/data-processing.md
> +Data in Stardust is published via [Tagged Data Payloads](https://github.com/iotaledger/tips/blob/main/tips/TIP-0023/tip-0023.md), which are treated
Ser, when use our Wiki? :sadness:

```suggestion
Data in Stardust is published via [Tagged Data Payloads](https://wiki.iota.org/shimmer/tips/tips/TIP-0023), which are treated
```

2023-04-16 16:36 UTC, Dr-Electron commented on shimmer/develop/explanations/what-is-stardust/data-processing.md
Nice article.Maybe out of the scope of this article, but should the fact that the Tangle doesn‘t store data blocks be more prominent? And also that storing data in utxo may be a (costlier) alternative?

2023-04-20 15:56 UTC, lucas-tortora commented on shimmer/develop/explanations/what-is-stardust/data-processing.md
We can certainly include it. Can you point me to a doc where I can retrieve the specs?

2023-04-20 17:29 UTC, Dr-Electron commented on shimmer/develop/explanations/what-is-stardust/data-processing.md
Not sure if there is any good specs for that.
Just the tip for a [tagged block](https://wiki.iota.org/tips/tips/TIP-0023/) (which will be completely pruned by nodes) and the [metadata feature](https://wiki.iota.org/tips/tips/TIP-0018/#metadata-feature) in outputs (which costs storage deposit and therefore won't be pruned)

2023-04-20 18:29 UTC, Dr-Electron commented on shimmer/develop/explanations/what-is-stardust/data-processing.md
Great work

2023-04-21 13:54 UTC, Dr-Electron requested changes
Do you except me to go through all of this 😅 .

Mostly is just moved so I tried to give newly added stuff a quick check. And most of it looks fine. 

Can you do one thing tho please?
Update all tips links to use the wiki links. Thanks

2023-04-21 13:54 UTC, Dr-Electron commented on shimmer/develop/explanations/what-is-stardust/dynamic-pow.md
> +Proof of Work (PoW) is currently employed in IOTA for congestion control. Every block must include a small amount of
Can we add the first line of this page up front? Seems weird to describe a non existing feature

2023-04-21 13:54 UTC, Dr-Electron commented on shimmer/develop/explanations/what-is-stardust/output-features.md
> +To read more about outputs, the Stardust ledger and tokenization concepts check out [TIP-18](https://github.com/lzpap/tips/blob/master/tips/TIP-0018/tip-0018.md).
```suggestion
To read more about outputs, the Stardust ledger and tokenization concepts check out [TIP-18](https://wiki.iota.org/tips/tips/TIP-0018).
```

2023-04-21 13:57 UTC, Dr-Electron requested changes
Also please remove the Shimmer EVM stuff. Guess it got stuck in this branch. I force pushed to main 😅

2023-04-21 15:03 UTC, Dr-Electron requested changes

2023-04-21 15:03 UTC, Dr-Electron commented on shimmer/develop/how-tos/nft/nft-as-a-wallet.mdx
> +for IOTA and [TIP-32](https://wiki.iota.org/shimmer/tips/tips/TIP-0032/#global-parameters)
```suggestion
[TIP-22](https://wiki.iota.org/shimmer/tips/tips/TIP-0022#detailed-design)
for IOTA and [TIP-32](https://wiki.iota.org/shimmer/tips/tips/TIP-0032#global-parameters)
```

2023-04-21 15:03 UTC, Dr-Electron commented on shimmer/develop/how-tos/nft/nft-collections.mdx
> +[TIP-32](https://wiki.iota.org/shimmer/tips/tips/TIP-0032/#global-parameters) Shimmer)
```suggestion
([TIP-22](https://wiki.iota.org/shimmer/tips/tips/TIP-0022#detailed-design) IOTA,
[TIP-32](https://wiki.iota.org/shimmer/tips/tips/TIP-0032#global-parameters) Shimmer)
```

2023-04-21 15:03 UTC, Dr-Electron commented on shimmer/develop/how-tos/output-unlock-conditions/expiration.mdx
> +The first new _Unlock Condition_ we are going to look at is the [Expiration Unlock Condition](https://wiki.iota.org/shimmer/tips/tips/TIP-0018/#expiration-unlock-condition).
```suggestion
The first new _Unlock Condition_ we are going to look at is the [Expiration Unlock Condition](https://wiki.iota.org/shimmer/tips/tips/TIP-0018#expiration-unlock-condition).
```

2023-04-21 15:03 UTC, Dr-Electron commented on shimmer/develop/how-tos/output-unlock-conditions/timelock.mdx
> +With Stardust, you can lock funds away based on time. When an output has a [Timelock Unlock Condition](https://wiki.iota.org/shimmer/tips/tips/TIP-0018/#timelock-unlock-condition)
```suggestion
With Stardust, you can lock funds away based on time. When an output has a [Timelock Unlock Condition](https://wiki.iota.org/shimmer/tips/tips/TIP-0018#timelock-unlock-condition)
```

2023-04-21 15:03 UTC, Dr-Electron commented on shimmer/develop/how-tos/simple-transfer.mdx
> +In Stardust, you can create a simple transfer using a [Basic Output](https://wiki.iota.org/shimmer/tips/tips/TIP-0018/#basic-output).
```suggestion
In Stardust, you can create a simple transfer using a [Basic Output](https://wiki.iota.org/shimmer/tips/tips/TIP-0018#basic-output).
```

2023-04-23 19:11 UTC, Dr-Electron approved these changes

2023-04-24 11:43 UTC, merged